version: "2"
services:
  react:
    image: bayesimpact/covid
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    tty: true
    ports:
      - "3000:80"
    volumes:
    - ../bob_emploi/frontend/client/ssl:/etc/ssl/webpack-dev:ro
    - ./src:/usr/app/src
    - ./package.json:/usr/app/package.json:ro
    - ./tsconfig.json:/usr/app/tsconfig.json:ro
    # For linting.
    - ./.eslintrc.json:/usr/app/.eslintrc.json:ro
    - ./.eslintignore:/usr/app/.eslinignore:ro
